# Generated by Django 5.2.17 on 2026-10-01 00:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_default=django.db.models.functions.datetime.Now(),
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("TRAVEL", "Travel"),
                            ("MEAL", "Meal"),
                            ("EQUIPMENT", "Equipment"),
                        ],
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(db_default="EUR", default="EUR", max_length=3),
                ),
                ("expense_date", models.DateField()),
                ("description", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("REIMBURSED", "Reimbursed"),
                        ],
                        db_default="DRAFT",
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, db_default="", default=""),
                ),
                ("reimbursed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "expenses_expense",
                "ordering": ["-expense_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentExpense",
            fields=[
                (
                    "expense_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="expenses.expense",
                    ),
                ),
                ("item_name", models.CharField(max_length=150)),
                ("serial_no", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "expenses_equipmentexpense",
            },
            bases=("expenses.expense",),
        ),
        migrations.CreateModel(
            name="MealExpense",
            fields=[
                (
                    "expense_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="expenses.expense",
                    ),
                ),
                ("attendees", models.PositiveSmallIntegerField()),
            ],
            options={
                "db_table": "expenses_mealexpense",
            },
            bases=("expenses.expense",),
        ),
        migrations.CreateModel(
            name="TravelExpense",
            fields=[
                (
                    "expense_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="expenses.expense",
                    ),
                ),
                ("distance_km", models.DecimalField(decimal_places=1, max_digits=8)),
                ("destination", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "expenses_travelexpense",
            },
            bases=("expenses.expense",),
        ),
    ]
