# Generated by Django 5.2.17 on 2026-09-12 11:05

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("expenses", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_%(app_label)s.%(class)s_set+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="users.project",
            ),
        ),
        migrations.AddConstraint(
            model_name="mealexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("attendees__gte", 1)), name="meal_attendees_min_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="travelexpense",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance_km__gt", 0)),
                name="travel_distance_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(fields=["status"], name="expense_status_idx"),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["employee", "-expense_date"], name="expense_employee_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["project", "status"], name="expense_project_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.search.SearchVector(
                    "description", config="simple"
                ),
                name="expense_description_fts",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="expense_amount_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(("type__in", ["TRAVEL", "MEAL", "EQUIPMENT"])),
                name="expense_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["DRAFT", "SUBMITTED", "APPROVED", "REJECTED", "REIMBURSED"],
                    )
                ),
                name="expense_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "REJECTED"), _negated=True),
                    models.Q(("rejection_reason", ""), _negated=True),
                    _connector="OR",
                ),
                name="expense_rejection_has_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="expense",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["APPROVED", "REJECTED", "REIMBURSED"]),
                        _negated=True,
                    ),
                    ("decided_at__isnull", False),
                    _connector="OR",
                ),
                name="expense_decided_has_timestamp",
            ),
        ),
    ]
